### ISSUE TITLE
Rebuild images in ibmsemeruruntime repos

### ISSUE THREAD

**Issue by leochr** [ibmruntimes/Semeru-Runtimes#10]
The images in [ibmsemeruruntime](https://hub.docker.com/u/ibmsemeruruntime) are at least a month old. When will they be rebuilt? How frequently are they built? Even if there are no changes to the Java version, a rebuild is necessary to pick up any fixes from the base layers (i.e. UBI).

Liberty images use Java 8 and 11 UBI images and require the base images to be updated to resolve vulnerabilities in UBI. Thank you.

@AdamBrousseau

**Comment by mstoodle** [comment]
Hi @leochr those are unofficial images we set up until we had official images created. We aren't intending to keep them going now that we have official images. See [ibm-semeru-runtimes official images](https://hub.docker.com/_/ibm-semeru-runtimes)

**Comment by mstoodle** [comment]
for UBI images there is also the Red Hat registry: [registry.connect.redhat.com/ibm/ibm-semeru-runtime-open-jdk-11-ubi](registry.connect.redhat.com/ibm/ibm-semeru-runtime-open-jdk-11-ubi)

**Comment by leochr** [comment]
Hi Mark (@mstoodle), Thank you for the response!

We are using [official ibm-semeru-runtimes images](https://hub.docker.com/_/ibm-semeru-runtimes) to build Liberty's Ubuntu-based images. But UBI and UBI-min images are not available from that repository (Docker Hub limitation in general for UBI images I believe).

Red Hat registry only contains Semeru images for amd64. We need ppc64le and s390x as well. Do they contain JDK or JRE? We need JDK on UBI and JRE on UBI-min. We'll be happy to switch repos, but we need the equivalents to what we are using now. Could you please offer what's missing? Until then, could the [current repo](https://hub.docker.com/u/ibmsemeruruntime) be maintained to keep them up to date? Thank you!

cc @nottycode @gcharters

**Comment by verymahler** [comment]
The files for Java 17 on UBI seem to be in the repository for a month already

https://github.com/ibmruntimes/semeru-containers/tree/ibm/17/jre/ubi
https://github.com/ibmruntimes/semeru-containers/tree/ibm/17/jre/ubi-minimal
https://github.com/ibmruntimes/semeru-containers/tree/ibm/17/jdk/ubi
https://github.com/ibmruntimes/semeru-containers/tree/ibm/17/jdk/ubi-minimal

They just don't seem to be registered in the [hotspot.config](https://github.com/ibmruntimes/semeru-containers/blob/ibm/config/hotspot.config)

Is this the only thing still preventing them from being hosted on DockerHub?

**Comment by thomseno** [comment]
Would like to see UBI flavored images of Java 11 as well.

**Comment by leochr** [comment]
Thank you for publishing the Java images (for 8/11/17 JDK/JRE on ubi/ubi-min) to `icr.io`. Appreciate it!
