### ISSUE TITLE
Is there any plan to support Linux repo?

### ISSUE THREAD

**Issue by abcfy2** [ibmruntimes/Semeru-Runtimes#14]
E.g: Ubuntu, Debian, RHEL/CentOS Linux repositories?

So we can use package manager to manage packages, like `apt`/`dnf`/`yum` and so on.

**Comment by AdamBrousseau** [comment]
@abcfy2 It is on our roadmap this year. At the moment we only build rpms. If you'd like other Linux packages I would encourage you to open another issue as well to help show the need for those.

**Comment by abcfy2** [comment]
Thanks.
