### ISSUE TITLE
Add manifest for multi-arch images in icr.io

### ISSUE THREAD

**Issue by leochr** [ibmruntimes/Semeru-Runtimes#16]
First of all, thank you for building and pushing Java 8, 11, and 17 images for amd64, p, and z platforms to icr.io.

Please add the manifest for the multi-arch images.

Getting the below error due to missing manifest. 

```
> docker pull icr.io/appcafe/ibm-semeru-runtimes:open-11-jdk-ubi
Error response from daemon: manifest for icr.io/appcafe/ibm-semeru-runtimes:open-11-jdk-ubi not found: manifest unknown: manifest unknown
```

Referencing the image for a particular platform (i.e *-amd64) is not ideal, because extending images (i.e. Liberty) should be able to build multi-arch images using the same Dockerfile

@AdamBrousseau

**Comment by mstoodle** [comment]
@narkedi can you investigate please?

**Comment by narkedi** [comment]
@leochr Updated the manifest for multi-arch images and pushed them to ICR.io. 

$ docker pull icr.io/appcafe/ibm-semeru-runtimes:open-11-jdk-ubi
Trying to pull icr.io/appcafe/ibm-semeru-runtimes:open-11-jdk-ubi...
Getting image source signatures
Copying blob 1cd57985bfbe skipped: already exists  
Copying blob a069b9bde9e3 skipped: already exists  
Copying blob 1922eddd1c16 skipped: already exists  
Copying blob 8912bed47435 skipped: already exists  
Copying blob ab39b4d6308f skipped: already exists  
Copying config 0b73956c21 done  
Writing manifest to image destination
Storing signatures
0b73956c21775935dfe4990ca93ffc19b3ab5f649f6b6b9132ed0b3d6fae49ea

Please note that the versions of JDK8, 11 and 17 are also updated.

**Comment by leochr** [comment]
@narkedi Thank you! We'll switch to these images to build Liberty images.
