### ISSUE TITLE
Update images to UBI 8.5

### ISSUE THREAD

**Issue by leochr** [ibmruntimes/Semeru-Runtimes#19]
Some CVE fixes are not in UBI 8.4. Please update to 8.5. It's urgent as some high-severity fixes are needed by customers. 

@narkedi @AdamBrousseau

**Comment by narkedi** [comment]
@leochr UBI is upgraded to 8.5, and the images are pushed to ICR.io. Please let us know incase of any issues. Thanks !!

**Comment by leochr** [comment]
@narkedi Thank you! We'll rebuild Liberty images to pick up the updates.
