### ISSUE TITLE
Checksums from AdoptOpenJDK API doesn't match

### ISSUE THREAD

**Issue by richardlau** [ibmruntimes/Semeru-Runtimes#20]
The `checksum` field in the metadata returned by
- Java 8, Linux s390x: https://api.adoptopenjdk.net/v3/assets/feature_releases/8/ga?architecture=s390x&image_type=jre&jvm_impl=openj9&os=linux&project=jdk&heap_size=normal&page_siz1&sort_method=DEFAULT&sort_order=DESC&vendor=adoptopenjdk
- Java 17, Linux s390x: https://api.adoptopenjdk.net/v3/assets/feature_releases/17/ga?architecture=s390x&image_type=jre&jvm_impl=openj9&os=linux&project=jdk&heap_size=normal&page_siz1&sort_method=DEFAULT&sort_order=DESC&vendor=adoptopenjdk

Doesn't match the `sha256sum` of the downloaded binary.

e.g. for https://api.adoptopenjdk.net/v3/assets/feature_releases/8/ga?architecture=s390x&image_type=jre&jvm_impl=openj9&os=linux&project=jdk&heap_size=normal&page_siz1&sort_method=DEFAULT&sort_order=DESC&vendor=adoptopenjdk:
- `checksum` field in metadata: cdfc4712ee9aba8e211e9949ac0c2dc85289d301a735a95d36b7555912d56c18
- checksum from the file downloaded in `checksum_link` (`.sha256.txt` file):  f711dbcacc0964efcf8354eace0b1d2a3e7f58271612430745b4d4b986fdc63d
- `sha256sum` checksum of the downloaded binary: f711dbcacc0964efcf8354eace0b1d2a3e7f58271612430745b4d4b986fdc63d
- `sha256` field from the metadata (`.json`) downloaded from the `metadata_link`: f711dbcacc0964efcf8354eace0b1d2a3e7f58271612430745b4d4b986fdc63d

**Comment by AdamBrousseau** [comment]
Thanks for finding and raising this issue Richard.

Looks like the API is picking up the *.sig.json file instead of the tar.gz.json. The sig json has the checksum of the sig file. I think we can simply stop producing the sig.json files as they shouldn't be needed for anything. I will have this included in the next release.

**Comment by AdamBrousseau** [comment]
The change has been delivered. This will be fixed in the next release.

**Comment by AdamBrousseau** [comment]
Just to note that the April release is delivered and we no longer produce *sig.json files.
