### ISSUE TITLE
Ubuntu images for open edition in icr.io

### ISSUE THREAD

**Issue by leochr** [ibmruntimes/Semeru-Runtimes#21]
Some Semeru images for Ubuntu are in icr.io, but only for the certified edition (i.e. `icr.io/appcafe/ibm-semeru-runtimes:certified-11-jdk-ubuntu`)

Could you please publish Ubuntu-based images for the open edition as well to icr.io? 

We want to publish Ubuntu-based images for Liberty to icr.io and building them using Semeru images in icr.io (like UBI) is ideal as opposed to using Docker Hub images as base. CISO has advised to stop using Docker Hub ([here](https://w3.ibm.com/w3publisher/supplier-security-risk-management/critical-software/cicd-pipeline) - Build automation: _DockerHub is not allowed_).

Here are the Semeru images Liberty uses (in case it helps you to prioritize)
ibm-semeru-runtimes:open-8-jre-focal
ibm-semeru-runtimes:open-11-jre-focal
ibm-semeru-runtimes:open-17-jre-focal

Thank you

@narkedi @AdamBrousseau

**Comment by narkedi** [comment]
@leochr Missed this issue, we will start pushing the images to ICR.io at the earliest. Will keep this issue updated with the details. Thanks !!

**Comment by narkedi** [comment]
Closing this issue, as the images are published at ICR.io.
