### ISSUE TITLE
Update Ubuntu images to 22.04

### ISSUE THREAD

**Issue by petrdvorak** [ibmruntimes/Semeru-Runtimes#31]
Currently, IBM Semeru Runtimes are available for Ubuntu 20.04, which contains vulerabilities. If possible, could you please bump version to 22.04? Base Adoptium images are already prepared.

**Comment by narkedi** [comment]
Images are updated and published at Dockerhub and ICR.io. Hence closing the issue !!

**Comment by petrdvorak** [comment]
Thank you! 😊
