### ISSUE TITLE
Support arm64

### ISSUE THREAD

**Issue by leochr** [ibmruntimes/Semeru-Runtimes#33]
Please provide arm64 based images for Semeru open edition on UBI and UBI-min. This is needed to provide arm64 based Liberty images.

**Comment by narkedi** [comment]
Support for ARM64 images on UBI & UBI-min are enabled and published at icr.io. Please re-open the issue or raise a new one incase of any issues. Thanks !!!

**Comment by leochr** [comment]
Thank you @narkedi!
