### ISSUE TITLE
Latest ibm-semeru-runtimes:open-11-jre seems corrupt

### ISSUE THREAD

**Issue by clloydaccanto** [ibmruntimes/Semeru-Runtimes#35]
Running `java` on the latest image gives error `Port Library failed to initialize: -86`. e.g. to reproduce:
```
$ docker run ibm-semeru-runtimes:open-11-jre java -version
Error: Port Library failed to initialize: -86
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Would expect more like this, e.g. when running against the previous stable version
```
$ docker run ibm-semeru-runtimes:open-11.0.16_8-jre java -version
openjdk version "11.0.16" 2022-07-19
IBM Semeru Runtime Open Edition 11.0.16.0 (build 11.0.16+8)
Eclipse OpenJ9 VM 11.0.16.0 (build openj9-0.33.0, JRE 11 Linux amd64-64-Bit Compressed References 20220804_491 (JIT enabled, AOT enabled)
OpenJ9   - 04a55b45b
OMR      - b58aa2708
JCL      - ab74d97849 based on jdk-11.0.16+8)
```

**Comment by AdamBrousseau** [comment]
Also would like to confirm where you are pulling your container from? DockerHub or IBM Container Registry.

**Comment by clloydaccanto** [comment]
Thanks for reply. I should have said this was linux/amd64. And pulled from dockerhub. More specifically:
```
$ docker run ibm-semeru-runtimes@sha256:fca8e02a77c04a09e5c49707d339e912acaad92aa8a1bd5452bf1191200e3a71 java -
version
Unable to find image 'ibm-semeru-runtimes@sha256:fca8e02a77c04a09e5c49707d339e912acaad92aa8a1bd5452bf1191200e3a71' locally
docker.io/library/ibm-semeru-runtimes@sha256:fca8e02a77c04a09e5c49707d339e912acaad92aa8a1bd5452bf1191200e3a71: Pulling from library/ibm-semeru-runtimes
2b55860d4c66: Already exists
324c05aec43f: Already exists
d5ecfb19bb22: Already exists
76bc10dfc48f: Already exists
Digest: sha256:fca8e02a77c04a09e5c49707d339e912acaad92aa8a1bd5452bf1191200e3a71
Status: Downloaded newer image for ibm-semeru-runtimes@sha256:fca8e02a77c04a09e5c49707d339e912acaad92aa8a1bd5452bf1191200e3a71
Error: Port Library failed to initialize: -86
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by narkedi** [comment]
@clloydaccanto I am able to run it without any issues atleast. 

snarkedi@Suryanarayanas-MacBook-Pro ~ % docker run ibm-semeru-runtimes@sha256:fca8e02a77c04a09e5c49707d339e912acaad92aa8a1bd5452bf1191200e3a71 java -version
openjdk version "11.0.16.1" 2022-08-12
IBM Semeru Runtime Open Edition 11.0.16.1 (build 11.0.16.1+1)
Eclipse OpenJ9 VM 11.0.16.1 (build openj9-0.33.1, JRE 11 Linux amd64-64-Bit Compressed References 20220818_500 (JIT enabled, AOT enabled)
OpenJ9   - 1d9d16830
OMR      - b58aa2708
JCL      - 84b84a0409 based on jdk-11.0.16.1+1)

**Comment by linuxhelf** [comment]
@clloydaccanto which version of docker are you running? Is it below 20.10.10?
I believe this is because the latest image uses Ubuntu Jammy as the base and it was focal before (according to a quick look at the tags on docker-hub), this leeds to problems with older docker version, see https://docs.linuxserver.io/faq
i can reproduce this with an older docker version and image open-11-jre, but open-11-jre-focal runs fine

**Comment by narkedi** [comment]
Thanks @linuxhelf this is some good finding.

**Comment by clloydaccanto** [comment]
good suggestion @linuxhelf! Yes I was running docker `20.10.5` and you were absolutely spot on, upgrading to `20.10.18` resolves the issue for me. So that absolutely looks like it.

Thanks everyone for your input, much appreciated. I'll either upgrade docker on my environments or look to use `open-11-jre-focal`
