### ISSUE TITLE
Semeru 17 macOS x64 JRE tar.gz download is a .sig file

### ISSUE THREAD

**Issue by pshipton** [ibmruntimes/Semeru-Runtimes#40]
On the Semeru download page, the Semeru 17.0.5 macOS x64 JRE tar.gz link is to the .sig file instead of the .tar.gz file.

**Comment by AdamBrousseau** [comment]
Good catch. Has been like that on that package since we added sig links. Will be updated later today.

**Comment by AdamBrousseau** [comment]
Done
