### ISSUE TITLE
Validate that the manifests match platform images

### ISSUE THREAD

**Issue by leochr** [ibmruntimes/Semeru-Runtimes#42]
As the manifest-related issues have affected images on multiple occasions, it'll be good to validate, as part of the Semeru builds,  that the platform images and manifest matches

@narkedi @AdamBrousseau

**Comment by narkedi** [comment]
@leochr Apologies and I agree. We actually amend the manifest for every release with the new images. Looks like its better to delete the existing manifest and create it afresh. Will see that its done this way going forward.

**Comment by narkedi** [comment]
This issue is fixed, hence closing it. Thanks !!

**Comment by leochr** [comment]
@narkedi just wanted to check if there is some manifest check in place now to avoid mismatch of digest values? we'll be interested to have something similar for Liberty images. Thanks
