### ISSUE TITLE
17 is not a valid tag as implied in the example

### ISSUE THREAD

**Issue by sailormurph** [ibmruntimes/Semeru-Runtimes#45]
11 is not a valid tag as implied in the example located at:
https://hub.docker.com/_/ibm-semeru-runtimes

> To run a pre-built japp.jar file with the latest OpenJDK 11, use the following Dockerfile:
> FROM ibm-semeru-runtimes:11

None of the pure version number tags seem to be valid.

**Comment by narkedi** [comment]
@sailormurph I will check on this and if the tags need to be updated, will do so. Thanks !!

**Comment by arthurdm** [comment]
I've hit this issue as well.  Tags are still incorrect on the main page.

**Comment by jayasg12** [comment]
Hi @sailormurph @arthurdm example is now updated to reflect correct tag  in main page : 
https://hub.docker.com/_/ibm-semeru-runtimes

FROM ibm-semeru-runtimes:open-11-jdk
RUN mkdir /opt/app
COPY japp.jar /opt/app
CMD ["java", "-jar", "/opt/app/japp.jar"]

**Comment by mstoodle** [comment]
Thanks @jayasg12 and thanks @sailormurph and @arthurdm for keeping us honest!
