### ISSUE TITLE
jdk11 & 17 for macOS

### ISSUE THREAD

**Issue by p-linnane** [ibmruntimes/Semeru-Runtimes#46]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. I am wondering if there will be .pkg releases for jdk11 and jdk17 on aarch64. We are currently not able to update our cask files to the latest releases since there are only .pkg files for x86_64. Thanks!

**Comment by AdamBrousseau** [comment]
Hi @p-linnane .
There will be shortly. Previously our Mac on aarch64 support was flagged as ea. The October release (11.0.17 and 17.0.5) we planned on removing the ea flag but we ran into some issues getting it released on time. It should be released soon though.
I had previously warned on a [PR](https://github.com/Homebrew/homebrew-cask/pull/130231) trying to add aarch64 support to homebrew that it was ea, but then another [PR](https://github.com/Homebrew/homebrew-cask/pull/134710) got in.

**Comment by p-linnane** [comment]
Ah yes, I remember our conversation on that now. Thank you for the update and I will continue to monitor.
