### ISSUE TITLE
Update to OpenJ9 v0.36.1

### ISSUE THREAD

**Issue by Herr-Sepp** [ibmruntimes/Semeru-Runtimes#47]
Is there any rule when the JVM is updated inside the images?

Currently it is not yet the latest release of OpenJ9
e.g.
open-17-jre-focal
ENV JAVA_VERSION=jdk-17.0.5+8_openj9-0.35.0

**Comment by AdamBrousseau** [comment]
OpenJ9 declared GA last week. IBM has the GA levels built and should be releasing early this coming week. Containers should be updated shortly after those releases are available.

**Comment by Herr-Sepp** [comment]
Ah ok, sorry. 
I just saw the "release" for openj9 in the github repository last week and wondered why the image didn't include the "release" yet.
