### ISSUE TITLE
Docker: arm64 builds

### ISSUE THREAD

**Issue by FireMasterK** [ibmruntimes/Semeru-Runtimes#5]
Title!

https://www.phoronix.com/scan.php?page=news_item&px=Eclipse-OpenJ9-v0.29

**Comment by AdamBrousseau** [comment]
Hi @FireMasterK ,
Our Semeru Open Edition release is in progress. We expect it will be ready by the end of the week. Docker containers, including aarch64/arm64 will follow shortly thereafter.

**Comment by AdamBrousseau** [comment]
We have added aarch64/arm64 containers to our Official DockerHub builds for the latest release.

**Comment by AdamBrousseau** [comment]
https://hub.docker.com/_/ibm-semeru-runtimes

**Comment by FireMasterK** [comment]
There seems to be an JVM error when using the arm64 image with buildx, the amd64 image works tho!

```
 > [linux/arm64 build 4/4] RUN chmod +x ./gradlew && ./gradlew shadowJar:
#16 1.290 Error: Port Library failed to initialize: -1
#16 1.302 Error: Could not create the Java Virtual Machine.
#16 1.302 Error: A fatal exception has occurred. Program will exit.
```

Full logs: https://github.com/TeamPiped/Piped-Backend/runs/4118862583?check_suite_focus=true#step:6:266
Dockerfile: https://github.com/TeamPiped/Piped-Backend/blob/master/Dockerfile.openj9

Do you know why this may be happening?

**Comment by AdamBrousseau** [comment]
@FireMasterK not sure. It is hard to tell what the problem is as the vm is not initialized enough to collect any useful data at that point in time. Could you add a simple `java -version` before that step to make sure java is functioning? Could you also try running Gradle with Semeru on arm64 outside of Docker?

**Comment by FireMasterK** [comment]
>Could you add a simple java -version before that step to make sure java is functioning?

Seems to be the same error:
```
 => ERROR [build 4/5] RUN java -version                                                                                                                                                                       0.4s
------                                                                                                                                                                                                             
 > [build 4/5] RUN java -version:
#11 0.409 Error: Port Library failed to initialize: -1
#11 0.413 Error: Could not create the Java Virtual Machine.
#11 0.413 Error: A fatal exception has occurred. Program will exit.
------
error: failed to solve: executor failed running [/bin/sh -c java -version]: exit code: 1
```

>Could you also try running Gradle with Semeru on arm64 outside of Docker?

Unfortunately, I don't have any environment to do this.


To reproduce this create a Dockerfile with:
```
FROM ibm-semeru-runtimes:open-11-jdk

RUN java -version
```

Install QEMU and docker buildx and run the following:
```
docker run --privileged --rm tonistiigi/binfmt --install all
docker buildx build --platform linux/arm64 -t test .
```

**Comment by pshipton** [comment]
@knn-k have you ever tried aarch64 under QEMU? I'm guessing that is the problem.

**Comment by knn-k** [comment]
No, I have never run the AArch64 runtime under QEMU.

**Comment by pshipton** [comment]
@FireMasterK can you get java to run under QEMU without docker? I made some changes to try and narrow down the problem, you can try a more recent build https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK11_aarch64_linux_OMR/29/OpenJ9-JDK11-aarch64_linux-20211109-180330.tar.gz

**Comment by knn-k** [comment]
A colleague of mine says he has run the AArch64 runtime using QEMU without Docker, and seen no particular failure.

**Comment by Software-Noob** [comment]
The 8 and 11 versions work fine on ARM64 (building multiplatform images for amd64/arm64 with QEMU). However, 16 doesn't have ARM64 in manifest and, as such, refuses to build. Is there a reason why 16 is explicitly missing arm64?

**Comment by AdamBrousseau** [comment]
OpenJ9 added arm64 support to the October release. Since 16.0.2 was the last release of jdk16 in July, there was/is no support in jdk16. Once OpenJ9 releases jdk17, arm64 will be available there too.

**Comment by AdamBrousseau** [comment]
@FireMasterK if you're still experiencing the issue, can you please open a new issue so we can track separately. Thanks.
