### ISSUE TITLE
OpenJDK 11.0.19

### ISSUE THREAD

**Issue by BriiSkii** [ibmruntimes/Semeru-Runtimes#52]
Hi there, 

Will there be a release for OpenJDK 11.0.19? If so, is there an ETA? 

Thanks!

**Comment by AdamBrousseau** [comment]
Hi @BriiSkii,

We are in the final stages of testing. We hope to have them out within the next week or two.

Cheers,
Adam

**Comment by BriiSkii** [comment]
Great. Thank you!
