### ISSUE TITLE
Rebuild ARM64 images to include UBI security fixes

### ISSUE THREAD

**Issue by leochr** [ibmruntimes/Semeru-Runtimes#55]
ARM64 images are using an older version of UBI image (8.8-854, which is 2 months old). Hence, some security fixes are missing.

Rebuilding the images should pick up the latest UBI level (8.8-1009)

FYI, Liberty images use these Semeru UBI images:
```
icr.io/appcafe/ibm-semeru-runtimes:open-8-jdk-ubi
icr.io/appcafe/ibm-semeru-runtimes:open-11-jdk-ubi
icr.io/appcafe/ibm-semeru-runtimes:open-17-jdk-ubi
```

**Comment by leochr** [comment]
fyi @narkedi @AdamBrousseau

**Comment by narkedi** [comment]
Hi @leochr The images are updated and published.

**Comment by leochr** [comment]
@narkedi thank you
