### ISSUE TITLE
Support ppc64le architecture for images based on jammy

### ISSUE THREAD

**Issue by leochr** [ibmruntimes/Semeru-Runtimes#56]
Images based on `jammy` are missing the ppc64le architecture in Docker Hub: https://hub.docker.com/_/ibm-semeru-runtimes/tags?page=1&name=jre-jammy

In particular, Liberty needs these images with ppc64le (along with amd64, s390x, arm64):
```
ibm-semeru-runtimes:open-8-jre-jammy
ibm-semeru-runtimes:open-11-jre-jammy
ibm-semeru-runtimes:open-17-jre-jammy
```

At the moment, Liberty uses the images based on _focal_ which supports ppc64le, but we received many customer requests to provide images based on jammy, but without the _ppc64le_ support, we can't switch to jammy.

FYI @narkedi @AdamBrousseau

**Comment by narkedi** [comment]
@leochr It shouldn't be anything different that would have changed this. I will take a look and update.

**Comment by leochr** [comment]
Thank you @narkedi. Seems to be related to this: https://github.com/docker-library/official-images/pull/13119

**Comment by narkedi** [comment]
I raised another PR to enable this platform. https://github.com/docker-library/official-images/pull/15105, images should be there once its merged.

**Comment by narkedi** [comment]
Images are now available. Closing the task.

**Comment by leochr** [comment]
@narkedi Thank you! We'll update Liberty images to use jammy
