### ISSUE TITLE
Update to the latest UBI 8 image (8.8-1067.1697633337 or later)

### ISSUE THREAD

**Issue by leochr** [ibmruntimes/Semeru-Runtimes#63]
Base UBI 8 image was updated recently and includes the fixes for some critical CVEs. It includes the fixes for some critical CVEs.

Please refresh the Semeru images to update to the latest UBI

@narkedi @AdamBrousseau

**Comment by jayasg12** [comment]
Below Semeru images in ICR are updated with latest UBI 8 version 
icr.io/appcafe/ibm-semeru-runtimes:open-17-jdk-ubi
icr.io/appcafe/ibm-semeru-runtimes:open-11-jdk-ubi
icr.io/appcafe/ibm-semeru-runtimes:open-8-jdk-ubi

**Comment by jayasg12** [comment]
Hi @leochr Semeru images will be updated every Friday. Last week we had plans to update it on Friday before which we got a request to update the images. And we got them updated on Friday. 

 It is going to be End of Friday IST , And if there is any server issue which blocks the update then it might move right.

**Comment by leochr** [comment]
@jayasg12 thank you. Closing as completed.
