### ISSUE TITLE
Any info source?

### ISSUE THREAD

**Issue by krismarc** [ibmruntimes/Semeru-Runtimes#76]
Hi there,

do we have any api/config file where all url to specific versions are stored for https://developer.ibm.com/languages/java/semeru-runtimes/downloads/ ?

I'd prefer to avoid creating pattern based tool using github tags/releases.

Anything which could help me fetching specific versions? :) Would be helpful for our CI/CD.

Best regards,
K.M.

**Comment by pshipton** [comment]
I'm guessing you are looking for the following URL which lets you download the latest builds automatically. If you want an example of another platform let me know. For a different version just change the number. You can only get Semeru Open Edition this way.

https://api.adoptopenjdk.net/v3/binary/latest/11/ga/linux/x64/jdk/openj9/normal/adoptopenjdk

https://azure-api.adoptopenjdk.net/q/swagger-ui/

**Comment by krismarc** [comment]
@pshipton, I was there! Seems like I am a bit lost in this JDK/JVM world with many manufacturers and all rebranding taking place.

Isn't it the api which powers https://adoptium.net/marketplace/ ? It's mentioned that you could get only certified version using it.

**Comment by AdamBrousseau** [comment]
I will add that the AdoptOpenJDK API is deprecated even though it continues to still be available and still host all the latest Semeru Open Edition releases. There is no guarantee it will be available forever but we have not been told if/when it will be discontinued. The Adoptium API, I believe, supports Semeru Certified Edition, although I am struggling to find the info on it at the moment. Some users have decided to use the GitHub API directly to get either or both Editions. (Adoptium and AdoptOpenJDK api's wrap the GitHub API).

**Comment by krismarc** [comment]
ok, so is my understanding correct that adoptium api is successor of adoptopenjdk one? and at least from swagger perspective it seems to support only hotspot version and there's nothing about openj9?

**Comment by AdamBrousseau** [comment]
https://marketplace-api.adoptium.net/q/swagger-ui/

**Comment by krismarc** [comment]
thx! I was checking this one:
https://api.adoptium.net/q/swagger-ui/

**Comment by AdamBrousseau** [comment]
Sounds like I can close this then.
