### ISSUE TITLE
Semeru runtimes site filters do not work

### ISSUE THREAD

**Issue by jacobwdv** [ibmruntimes/Semeru-Runtimes#83]
When I go to the Semeru runtimes site: https://developer.ibm.com/languages/java/semeru-runtimes/downloads/

The filters don't work. For example, selecting OS or Java version will not filter the data, only Java 21 is shown regardless of what is selected.

**Comment by AdamBrousseau** [comment]
Cc @davehobbs 

Thanks for reporting this issue. I believe a ticket has already been raised in IBM to the team who maintains the back end website infrastructure.

**Comment by davehobbs** [comment]
@jacobwdv This issue has been fixed. Sorry for the inconvenience.

.cc @AdamBrousseau

**Comment by AdamBrousseau** [comment]
Site is fixed.
