### ISSUE TITLE
NullPointerException thrown in StackTraceElement.hashCode with IBM Semeru runtime 11.0.13 

### ISSUE THREAD

**Issue by dynatrace-peterlang** [ibmruntimes/Semeru-Runtimes#9]
StackTraceElement.hashCode throws an unexpected NullPointerException in my application. 

I created a simple reproducer app (https://github.com/dynatrace-peterlang/exception-stacktraceelement-npe). 
If I run it with `IBM Semeru Runtime Open Edition 11.0.13.0 (build 11.0.13+8)` my app fails with a NullPointerException.
```
java.lang.NullPointerException
        at java.base/java.lang.StackTraceElement.hashCode(StackTraceElement.java:278)
        at java.base/java.util.HashMap.hash(HashMap.java:340)
        at java.base/java.util.HashMap.get(HashMap.java:553)
        at com.dynatrace.App.main(App.java:32)
```

**Comment by JasonFengJ9** [comment]
Is this an intermittent NPE?

**Comment by JasonFengJ9** [comment]
Created https://github.com/eclipse-openj9/openj9/issues/13941.

**Comment by dynatrace-peterlang** [comment]
> Is this an intermittent NPE?
No the NPE is always thrown.
