### ISSUE TITLE
can't open the exe file packaged by jpackage 

### ISSUE THREAD

**Issue by Xurhh** [ibmruntimes/Semeru-Runtimes#92]
I create the exe file "demo"successfully like this:
C:\Users\XRH\Desktop\bank> jpackage --name demo --input src --main-jar bank.jar --main-class Main.class   --win-console
before that,I successfully run the bank.jar
![image](https://github.com/user-attachments/assets/84aed641-4f42-41ac-8667-e6b0099bf623)

but after open the demo.exe, nothing happen, and I found a poccess"Installer of demo" keep running in the Taskmanager.

![issue2](https://github.com/user-attachments/assets/b2ee0e02-5cdc-48dd-9526-0f31f190c284)

how to solve it? thanks for helping

**Comment by pshipton** [comment]
It worked for me a couple of times and then I started getting the same as you described. Not sure what I changed or why that started to happen. You can remove "demo" from the list of installed apps in Windows settings, and then the installer works again to install it.

When it works, Windows asks for permission to install, and then it installs the app under `\Program Files`. You can run `\Program Files\demo\demo.exe` and the app should run. You can also avoid creating the installer and just create the packaged application by setting `--type app-image` on the jpackage command line.

**Comment by pshipton** [comment]
btw, I think you should specify `--main-class Main` otherwise you may get `Error: Could not find or load main class Main.class` when you run the app.

**Comment by Xurhh** [comment]
> It worked for me a couple of times and then I started getting the same as you described. Not sure what I changed or why that started to happen. You can remove "demo" from the list of installed apps in Windows settings, and then the installer works again to install it.
> 
> When it works, Windows asks for permission to install, and then it installs the app under . You can run and the app should run. You can also avoid creating the installer and just create the packaged application by setting on the jpackage command line.`\Program Files``\Program Files\demo\demo.exe``--type app-image`

thanks! I try the method ,but there's another problem that is when I run it:
C:\Users\XRH\Desktop\bank\src> jpackage --name demo --input . --win-console  --main-jar bank.jar --main-class Main --type app-image --dest "E:\myproject"
it create the packaged successfully,but there is a long classpath:
![issue3](https://github.com/user-attachments/assets/f70888be-4fcb-4a9e-9dc1-57b58be06844)
I put my .class file and .jar file in one folder"C:\Users\XRH\Desktop\bank\src" ,and use jpackage to pack it, maybe there is something wrong?

**Comment by pshipton** [comment]
I hit that problem too, you can't use the current directory as the input.

**Comment by Xurhh** [comment]
> I hit that problem too, you can't use the current directory as the input.

okok thanks！
